name = "IOM_newsAPI_query"
uuid = "2f70e6e1-4b7e-452a-8221-497046ae2690"
authors = ["your-name"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
